#!/bin/sh
set -e

case "$1" in
    configure)
	user="gearmand"
	group="gearmand"
	datadir="/var/lib/gearmand"
	logdir="/var/log/gearmand"
	rundir="/var/run/gearmand"

	if ! getent group "$group" > /dev/null 2>&1 ; then
	    addgroup --system "$group" --quiet
	fi

	if ! id "$user" > /dev/null 2>&1 ; then
	    adduser --system --home "$datadir" --no-create-home \
		--ingroup "$group" --disabled-password \
		--shell /bin/false "$user"
	fi

	install -d -o "$user" -g "$group" -m 0755 "$datadir"
	install -d -o "$user" -g "$group" -m 0755 "$logdir"
	install -d -o "$user" -g "$group" -m 0755 "$rundir"
    ;;
esac
